apiVersion: v1
kind: Service
metadata:
  name: my-service  # Replace with your desired service name
spec:
  selector:  # Defines pods to be included in the service
    app: my-flask-app  # Replace with the label used in your deployment
  ports:
    - port: {{ .Values.service.port }}  # Service port (exposed to external clients)
      targetPort: {{ .Values.service.targetport }}  # Port on which pods are listening (usually application port)